---
version: '3'
services:
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityX2.py:/freqtrade/NostalgiaForInfinityX2.py"
    command: >
      trade
      --strategy NostalgiaForInfinityX2
      --config user_data/data/pairlists.json
      --config user_data/data/kucoin-usdt-volume.json
      --config user_data/data/kucoin-blacklist.json
      --logfile user_data/logs/freqtrade.log